INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hungry Children", "Charity", 5000, 10/15/19, 11/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Disaster Relief", "Charity", 10000, 10/15/19, 12/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Identity Recovery", "Civil Services", 5000, 10/15/19, 11/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Futuristic Transportation Testing", "Science", 12000, 10/30/19, 1/30/20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Presidential Background Checks", "Civil Protection", 20000, 10/20/19, 06/20/20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sex Traffic Law Enforcement", "Civil Protection", 20000, 09/15/19, 10/15/20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Veterans Housing", "Civil Services", 15000, 10/15/19, 10/15/20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Worldly Plastic Reduction", "Civil Protection", 50000, 10/15/19, 10/15/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Climate Control", "Science", 25000, 10/15/19, 11/15/20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food and Water for All", "Charity", 50000, 10/15/19, 11/15/21);

INSERT INTO users (name, age) VALUES ("Steve", 22);
INSERT INTO users (name, age) VALUES ("Jackie", 32);
INSERT INTO users (name, age) VALUES ("Stan", 36);
INSERT INTO users (name, age) VALUES ("Holden", 62);
INSERT INTO users (name, age) VALUES ("Turner", 29);
INSERT INTO users (name, age) VALUES ("Jessica", 40);
INSERT INTO users (name, age) VALUES ("Rebecca", 32);
INSERT INTO users (name, age) VALUES ("Jackson", 35);
INSERT INTO users (name, age) VALUES ("Igrid", 25);
INSERT INTO users (name, age) VALUES ("Tammi", 37);
INSERT INTO users (name, age) VALUES ("Josh", 52);
INSERT INTO users (name, age) VALUES ("Kevin", 56);
INSERT INTO users (name, age) VALUES ("Lynn", 38);
INSERT INTO users (name, age) VALUES ("Liah", 32);
INSERT INTO users (name, age) VALUES ("Justin", 55);
INSERT INTO users (name, age) VALUES ("Angelica", 31);
INSERT INTO users (name, age) VALUES ("Morgan", 25);
INSERT INTO users (name, age) VALUES ("Stephen", 30);
INSERT INTO users (name, age) VALUES ("Cade", 59);
INSERT INTO users (name, age) VALUES ("Lauren", 42);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 20, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 10, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5500, 12, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5600, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8900, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5800, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3800, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1800, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2800, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 16, 1);
